comment django-ldapdb configuration in tests.settings because:
1) they are not used yet
2) they are breaking ALL the existing tests, needs to be fixed ASAP
The error is:
TransactionManagementError: Transaction managed block ended with pending COMMIT/ROLLBACK